robot_name: "schunk"

# Failsafe information
max_s_stop: 0.0
q_min_allowed: [-2.9, -1.8]
q_max_allowed: [2.9, 1.8]
v_max_allowed: [1.0, 1.0]
a_max_allowed: [10, 10]
j_max_allowed: [400, 400]
# Maximum long-term planning acc / jerk
a_max_ltt: [2, 2]
j_max_ltt: [15, 15]

nb_joints: 1

q1: [0.0]