# cutains information
measurement_error_pos: 0.0
measurement_error_vel: 0.0
delay: 0.0

# Names of joints in correct outputted order
joint_names: [
  "abdomen", "chest", "head", "hip", "lButtock", 
  "lCollar", "lFoot", "lForeArm", "lHand", "lShin",
  "lShldr", "lThigh", "neck", "rButtock", "rCollar",
  "rFoot", "rForeArm", "rHand", "rShin", "rShldr",
  "rThigh"
]
joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2
]

joint_a_max: [
  20, 20, 25, 20, 20, 
  20, 30, 50, 50, 30,
  50, 30, 25, 20, 20,
  30, 50, 50, 30, 50, 
  30
]
# All values are in the 95% Quantiles defined in DIN 33402-2
# There are no values about arm circumfence, so we take the leg values as overapproximation.
bodies:
  - name: "lUpperArm" 
    proximal: "lShldr"
    distal: "lForeArm"
    thickness: 0.108

  - name: "lLowerArm"
    proximal: "lForeArm"
    distal: "lHand"
    thickness: 0.068

  - name: "lHand"
    proximal: "lHand"
    distal: "lHand"
    thickness: 0.208

  - name: "rUpperArm" 
    proximal: "rShldr"
    distal: "rForeArm"
    thickness: 0.108

  - name: "rLowerArm"
    proximal: "rForeArm"
    distal: "rHand"
    thickness: 0.068

  - name: "rHand"
    proximal: "rHand"
    distal: "rHand"
    thickness: 0.208

  - name: "torso"
    proximal: "hip"
    distal: "neck"
    thickness: 0.193
  
  - name: "head"
    proximal: "head"
    distal: "head"
    thickness: 0.2

extremities:
  - name: "lArm"
    base: "lShldr"
    end: "lHand"
    length: 0.725 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    
  - name: "rArm"
    base: "rShldr"
    end: "rHand"
    length: 0.725 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.